pipeline:
  build:
    image: node:boron
    commands:
      - npm install --quiet
    when:
      event: tag

  publish:
    image: plugins/npm
    username: soapbubble
    email: mmorpheus.twitch.dev@gmail.com
    secrets: [ npm_password ]
    when:
      event: tag
