pipeline:
  build:
    image: node:boron
    commands:
      - npm install --quiet
    when:
      branch: master
      event: tag

  publish:
    image: plugins/npm
    secrets: [ npm_username, npm_password, npm_email ]
    when:
      branch: master
      event: tag
