pipeline:
  build:
    image: node:boron
    commands:
      - npm install --quiet
    when:
      event: tag

  publish:
    image: plugins/npm
    username: captemulation
    email: mmorpheus.twitch.dev@gmail.com
    tag: ${DRONE_TAG}
    secrets: [ npm_password ]
    when:
      event: tag
